services:
  - type: web
    name: battery-soh-api
    runtime: docker
    repo: https://github.com/delchere/Battery_SOH_Prediction
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 5000